name: Update config files
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
               
      - name: Download new files
        run: | 
          cd data
          sudo wget https://raw.githubusercontent.com/georgekart/RuBannedList/main/category-banned-ru -O category-banned-ru     

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
